-- Création de la table des commandes
create table public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  first_name text,
  last_name text,
  email text,
  whatsapp text,
  country text,
  plan text,
  price text,
  device_type text,
  mac_address text,
  adult_channels boolean,
  payment_status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Activer la sécurité (RLS)
alter table public.orders enable row level security;

-- Créer une politique pour permettre l'insertion publique (pour le formulaire de commande)
create policy "Enable insert for everyone" 
on public.orders for insert 
with check (true);

-- Créer une politique pour permettre la lecture publique (pour le dashboard admin simplifié)
create policy "Enable read access for everyone"
on public.orders for select
using (true);

-- Créer une politique pour permettre la mise à jour publique (pour le statut de paiement)
create policy "Enable update for everyone"
on public.orders for update
using (true);
